### ISSUE TITLE
Issue with "No turtles are connected"

### ISSUE THREAD

**Issue by TheSPREEGuy** [PrintedScript/turtle-control#10]
I have the turtle connected but it does not show up in the web page

turtle:
![image](https://user-images.githubusercontent.com/23518058/233818075-433e6438-8336-45a7-82c1-ae31deacb71a.png)
servers:
![image](https://user-images.githubusercontent.com/23518058/233818135-691c81cd-803f-41be-9f71-8a277121f7f6.png)
web page:
![image](https://user-images.githubusercontent.com/23518058/233818153-4cf5225f-35e0-4592-b61a-c299f81640d7.png)

**Comment by TheSPREEGuy** [comment]
I solved it my bad I had the modem firewall setup wrong lol

**Comment by Jackaroo05** [comment]
How do I fix the modem firewall?
